import { ReactQueryProviders } from '@/sdk/utility'
import './globals.scss'
import { LayoutClient } from './layout-client'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProviders>
          <LayoutClient />
          {children}
        </ReactQueryProviders>
      </body>
    </html>
  )
}
